Use correct git clone ... cmd; +cleanup

diff --git a/yocto/yocto_tools/host_setup_4yocto b/yocto/yocto_tools/host_setup_4yocto
--- a/yocto/yocto_tools/host_setup_4yocto
+++ b/yocto/yocto_tools/host_setup_4yocto
@@ -11,7 +11,7 @@ name=$(basename "$0")
 runcmd()
 {
 local DUMMY_RUN=0
-SEP="------------------------------"
+local SEP="------------------------------"
 [ $# -eq 0 ] && return
 echo "${SEP}
 $@"
@@ -25,13 +25,20 @@ echo "
 -----------------------------------------------------------------
 Getting host packages up-to-date now ..."
 runcmd "sudo apt update"
-runcmd "sudo apt-get install wget git-core diffstat unzip texinfo gcc-multilib \
-     build-essential socat cpio python python2.7 python3 python3-pip python3-pexpect \
-     xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev \
-     xterm g++ chrpath diffstat gawk zstd"
+# ref: https://docs.yoctoproject.org/current/brief-yoctoprojectqs/index.html
+runcmd "sudo apt install gawk wget git diffstat unzip texinfo gcc build-essential \
+		chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils \
+		iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 \
+		xterm python3-subunit mesa-common-dev zstd liblz4-tool"
+#runcmd "sudo apt-get install wget git-core diffstat unzip texinfo gcc-multilib \
+#     build-essential socat cpio python python2.7 python3 python3-pip python3-pexpect \
+#     xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev \
+#     xterm g++ chrpath diffstat gawk zstd"
 }
 
 # We use the 'poky' distro as a base reference
+# Parameters:
+#  $1 : Yocto rel name
 clone_yocto_poky()
 {
 [ $# -ne 1 ] && {
@@ -42,31 +49,41 @@ pwd
 echo "
 -----------------------------------------------------------------
 Will now clone yocto into dir ${YOCTO_DIR}"
-runcmd "cd ${YOCTO_DIR}"
+cd ${YOCTO_DIR} || exit 1
 runcmd "git clone -b $1 https://git.yoctoproject.org/poky"
+# TIP- if this doesn't work try substituting https:// with git:// (or vice-versa)
 [ ! -d "${YOCTO_DIR}"/poky ] && {
   echo "${name}: the dir \"${YOCTO_DIR}/poky\" isn't there, something's gone wrong, aborting..."
+  echo "TIP- try substituting https:// with git:// (or vice-versa)"
   exit 1
 }
-cd ${YOCTO_DIR}/poky
+cd ${YOCTO_DIR}/poky || exit 1
 
 echo "
 ${name}: We shall now show all the git tags and ask you to select one
  Press [Enter] to continue..."
 read -r
 git fetch --tags
-echo "Pick a tag: (scroll through all and then type a tag name, eg. yocto-3.0)"
+echo "Pick a tag: (scroll through all and then type a tag name, eg. kirkstone)"
 git tag
-echo "Pick a tag: (now type a tag name, eg. dunfell)
+echo "Pick a tag: (now type a tag name, eg. kirkstone)
 
-IMP TIP: usually, you should select the latest stable release (f.e. honister-nnn, ...)
+IMP TIP: usually, you should select the latest stable release (f.e. kirkstone / honister / ...)
 (can find the release name here: https://www.yoctoproject.org/ )
+Do NOT type the ver# after the name (i.e. just type 'kirkstone' for eg.)
 
 "
 read -r mytag
 
-MYBRANCH=mybranch01    # UPDATE as required
-runcmd "git checkout tags/${mytag} -b ${MYBRANCH}"
+echo "git checkout -t origin/${mytag} -b my-${mytag}"
+git checkout -t origin/${mytag} -b my-${mytag} || {
+  echo "${name}: something's gone wrong, aborting..."
+  exit 1
+}
+echo "The previous Git checkout command creates a local branch named my-${mytag}.
+The files available to you in that branch exactly match the repository’s files in the ${mytag} release branch.
+To keep it in sync simply do a 'git pull'
+"
 runcmd "git status"
 }
 
@@ -121,13 +138,15 @@ bitbake ${POKY_IMAGE_TO_BUILD}
 ### 'main' here
 
 ### Keep UPDATED !
-LATEST_YOCTO_RELNAME="honister"
-LATEST_YOCTO_RELVER="3.4.1"
+# ref: https://www.yoctoproject.org/software-overview/downloads/
+LATEST_YOCTO_RELNAME="kirkstone"
+LATEST_YOCTO_RELVER="4.0.4"
 ###
 [ $# -ne 2 ] && {
   echo "Usage: ${name} yocto-dir yocto-release-name-to-clone"
-  echo " yocto-dir : to create and populate with the Yocto project"
-  echo " yocto-release-name-to-clone : check latest (or whichever one you want) on https://www.yoctoproject.org/software-overview/downloads/
+  echo "This script requires two parameters"
+  echo "1. yocto-dir : to create and populate with the Yocto project (shouldn't already exist)"
+  echo "2. yocto-release-name-to-clone : check latest (or whichever one you want) on https://www.yoctoproject.org/software-overview/downloads/
    F.e. the latest (as of this script) is named '${LATEST_YOCTO_RELNAME}' ver $LATEST_YOCTO_RELVER)
    For this param, just specify the release name."
 
@@ -137,6 +156,19 @@ LATEST_YOCTO_RELVER="3.4.1"
   echo "${name}: the dir specified \"$1\" already exists, won't overwrite, aborting.."
   exit 1
 }
+
+echo -n "
+A quick check:
+This helper script has the latest Yocto release as:
+${LATEST_YOCTO_RELNAME} ver ${LATEST_YOCTO_RELVER}
+
+Is this correct? [y/n] "
+read re
+if [ "${re}" != "y" -a "${re}" != "Y" ]; then
+	echo "Ok, aborting. Pl update it in the script and rerun, thanks!"
+	exit 1
+fi
+
 YOCTO_DIR=$(realpath $1)
 YOCTO_RELNAME=$2
 echo "YOCTO_DIR = ${YOCTO_DIR} . Yocto release specified: ${YOCTO_RELNAME}"
