Mandate running from the YP workspace; then YOCTO_DIR env var isn't needed, BUILDDIR used

diff --git a/yocto/yocto_tools/yct_recipe_gen b/yocto/yocto_tools/yct_recipe_gen
--- a/yocto/yocto_tools/yct_recipe_gen
+++ b/yocto/yocto_tools/yct_recipe_gen
@@ -30,11 +30,11 @@ WARN=0
 #-- Create the conf/layer.conf file
 setup_conf_layer_file()
 {
-local conf_file=${YOCTO_DIR}/${LAYER}/conf/layer.conf
+local conf_file=${BUILDDIR}/${LAYER}/conf/layer.conf
 dprint "conf_file = ${conf_file}"
 echo
 echo "[+] Create layer's layer.conf file"
-[ -f "${YOCTO_DIR}"/"${LAYER}"/conf/layer.conf ] && {
+[ -f "${BUILDDIR}"/"${LAYER}"/conf/layer.conf ] && {
   QP
   echo " *WARNING* skipping as layer.conf file already exists:"
   ls -l "${conf_file}"
@@ -42,7 +42,7 @@ echo "[+] Create layer's layer.conf file"
   return
 }
 
-cd "${YOCTO_DIR}"/"${LAYER}" || exit 1
+cd "${BUILDDIR}"/"${LAYER}" || exit 1
 #pwd
 mkdir -p conf
 rm -f conf/layer.conf 2>/dev/null
@@ -115,7 +115,7 @@ echo
 echo "[+] Generate the layer's recipe file"
 
 local PV=0 PR=1
-local recipe_file=${YOCTO_DIR}/${LAYER}/recipes-${layer_token2}/${RCP_NAME}/${RCP_NAME}_${PV}.${PR}.bb
+local recipe_file=${BUILDDIR}/${LAYER}/recipes-${layer_token2}/${RCP_NAME}/${RCP_NAME}_${PV}.${PR}.bb
 
 # TODO : TEMP
 #rm -f ${recipe_file}
@@ -235,44 +235,30 @@ ls -l "${recipe_file}"
 ### 'main'
 
 which yad >/dev/null || {
-  echo "${name}: 'yad' (yet another dialog) util missing, pl install package and retry..."
+  echo "${name}: 'yad' (yet another dialog) util missing, pl install package and retry...
+(Yes, as of now at least, this script requires to be run in a GUI-only environment)"
   exit 1
 }
-
-set +u
-[ -z "${YOCTO_DIR}" ] && YOCTO_DIR=${YOCTO_PFX}
-set -u
-export YOCTO_DIR
-[ ! -d "${YOCTO_DIR}" ] && {
-  echo "${name}: ERROR: the default 'yocto' build area specified
- \"${YOCTO_DIR}\"
-does not exist (this default value is in the 'common' script).
-
-Pl setup the yocto workspace first and then run this tool...
-Tips:
-- override the YOCTO_DIR default by setting the env var YOCTO_DIR
-  prior to running this tool
-- for 'debug' mode, set the first parameter as '-d'
-Eg.
-  YOCTO_DIR=/opt/yocto_intel/poky/build ./${name} -d meta-mylayer1 afirstrecipe
-"
-  exit 1
+setup_env #-q  # from the 'common' script
+# By now, BUILDDIR is confirmed as okay; so lets proceed...
+[[ 0 -eq 1 ]] && {
+BUILDDIR=$(${PFX}/showvars2 |grep "^BUILDDIR" |awk -F'=' '{print $2}')
+[[ -z "${BUILDDIR}" ]] && failit "couldn't fetch value of BUILDDIR"
+IMAGE_BASENAME=$(${PFX}/showvars2 |grep "^IMAGE_BASENAME" |cut -d: -f2)
+[[ -z "${IMAGE_BASENAME}" ]] && failit "couldn't fetch value of IMAGE_BASENAME"
+MACHINE=$(${PFX}/showvars2 MACHINE |grep "^MACHINE" |cut -d: -f2|tail -n1)
+[[ -z "${MACHINE}" ]] && failit "couldn't fetch value of MACHINE"
 }
 
-echo " +++ NOTE Carefully Please +++
-The current yocto workspace settings are:
+export BUILDDIR
+echo "
++++ NOTE Carefully Please +++
+Your current Yocto 'build' dir (\$BUILDDIR) is
+\"${BUILDDIR}\"
 
- yocto 'build' dir = \"${YOCTO_DIR}\"
-
-[fyi, pwd = $(pwd)]
-
-This implies that the recipe dir tree and files will be created within the
-yocto 'build' dir displayed above.
-If this is fine, press [Enter] to continue,
-else press ^C to abort, then set (export) the environment variable YOCTO_DIR prior
-to running this tool and retry...
-
-Now press [Enter] to continue or ^C to abort ... "
+This implies that the recipe dir tree and files will be created within this
+Yocto 'build' dir displayed above.
+If this is fine, press [Enter] to continue, else press ^C to abort"
 read -r
 
 # usage check
@@ -312,13 +298,13 @@ export layer_token2=$(echo "${LAYER}" |cut -d"-" -f2)
 dprint "layer_token2 = ${layer_token2}"
 
 TOP=$(pwd)
-cd "${YOCTO_DIR}" || exit 1
+cd "${BUILDDIR}" || exit 1
 echo "Base Yocto workspace <pfx/build-dir> ::
-${YOCTO_DIR}
+${BUILDDIR}
 "
 
 #-- Create the basic tree
-RCP_FILES_DIR=${YOCTO_DIR}/${LAYER}/recipes-${layer_token2}/${RCP_NAME}/files
+RCP_FILES_DIR=${BUILDDIR}/${LAYER}/recipes-${layer_token2}/${RCP_NAME}/files
 dprint "RCP_FILES_DIR = ${RCP_FILES_DIR}"
 mkdir -p "${RCP_FILES_DIR}" || {
   echo "Creating recipe dir \"${RCP_FILES_DIR}\" failed, aborting..."
@@ -335,7 +321,7 @@ echo
 "
 echo "Layer \"${LAYER}\" recipe \"${RCP_NAME}\" setup:
 "
-tree "${YOCTO_DIR}"/"${LAYER}"/recipes-"${layer_token2}"
+tree "${BUILDDIR}"/"${LAYER}"/recipes-"${layer_token2}"
 
 cd "${TOP}"
 
