Minor fixes

diff --git a/yocto_tools/show_all_build_images b/yocto_tools/show_all_build_images
--- a/yocto_tools/show_all_build_images
+++ b/yocto_tools/show_all_build_images
@@ -1,7 +1,8 @@
 #!/bin/bash
 name=$(basename $0)
 source ./common || {
-  echo "${name}: could not source 'common', aborting..." ; exit 1
+  echo "${name}: warning: could not source 'common'..." #; exit 1
+  YOCTO_PFX=..   # assuming you're in the build dir
 }
 
 (
