Improved recipe generated..

diff --git a/yocto_tools/yct_recipe_gen b/yocto_tools/yct_recipe_gen
--- a/yocto_tools/yct_recipe_gen
+++ b/yocto_tools/yct_recipe_gen
@@ -2,7 +2,8 @@
 # yct_recipe_gen
 
 name=$(basename $0)
-source ./common || {
+PFX=$(dirname $(which $0))    # dir in which the common code and tools reside
+source ${PFX}/common || {
   echo "${name}: could not source 'common', aborting..." ; exit 1
 }
 WARN=0
@@ -94,7 +95,9 @@ local recipe_file=${YOCTO_PFX}/${BUILD_DIR}/${LAYER}/recipes-${layer_token2}/${R
 
 [ -f ${recipe_file} ] && {
   QP
-  echo " *WARNING* skipping as recipe file already exists:"
+  echo "
+*WARNING* skipping as recipe file already exists:
+"
   ls -l ${recipe_file}
   WARN=1
   return
@@ -110,11 +113,14 @@ local SRCURI_FILES
 for fname in $(cat ${tmpf})
 do
   #echo "fname : ${fname}"
-  SRCURI_FILES="${SRCURI_FILES} \\
-  file://${fname} \\"
+  SRCURI_FILES="${SRCURI_FILES} file://${fname}"
 done
+SRCURI_FILES="${SRCURI_FILES} \\"
 rm -f ${tmpf}
-#echo "SRCURI_FILES : ${SRCURI_FILES}"
+#echo "
+#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+#SRCURI_FILES : ${SRCURI_FILES}
+#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
 
 cat << @EOF@ > ${recipe_file}
 # Recipe generated by ${name}
@@ -137,22 +143,22 @@ RDEPENDS_\${PN} = ""
 
 # Location of files
 #  Tip: append '; unpack=0 \' to not unpack the file
-# IMP :: pl remove any extra '\' char at EOL (only 1 should be present)
-SRC_URI = "${SRCURI_FILES} \\
+SRC_URI = "${SRCURI_FILES}
    "
 
-# The FILE_\${PN} add is required to avoid the 'installed but not shipped in any package'
-# error
-#FILES_\${PN} += "\${base_prefix}/opt/myprj/*"
+# The FILE_\${PN} addition below is required to avoid the 'installed but not shipped in any package'
+# error; it's left commented out by default
+#FILES_\${PN} += "\${base_prefix}/${SRCURI_FILES}"
 
 IMAGE_FEATURES += ""
 
 S = "\${WORKDIR}"
-# Fyi, \${D} = \${WORKDIR}/image
+# FYI, \${S} = \${WORKDIR} = tmp/work/\${PACKAGE_ARCH}-poky-\${TARGET_OS}/\${PN}/\${PV}-\${PR}
+#  \${D} = \${WORKDIR}/image
 # f.e
 #  poky/rpi-build/tmp/work/aarch64-poky-linux/myprj/1.0-r0/image/
-#  [                      WORKDIR                              ][image]
-#      [build-dir][     tmp workdir          ][ pkgname ][rel# ][rootfs]
+#                 [               WORKDIR                 ][image]
+#      [build-dir][             tmp workdir               ]
 # [rootfs] is a 'partial' rootfs - one made for ONLY this recipe's rootfs
 # content! The final rootfs is a union of all the recipe/pkg [rootfs]'s
 
@@ -187,18 +193,28 @@ which yad >/dev/null || {
   exit 1
 }
 
-echo "              +++ NOTE Carefully pl +++
+[ ! -d ${YOCTO_PFX}/${BUILD_DIR} ] && {
+  echo "${name}: ERROR: the 'yocto' build area specified
+ \"${YOCTO_PFX}/${BUILD_DIR}\"
+does not exist. Pl setup the yocto workspace first and then run this tool...
+[go to the src file 'common' and fix the value of the variables
+YOCTO_PFX and BUILD_DIR there]"
+  exit 1
+}
+
+echo "              +++ !NOTE Carefully Please! +++
 The current yocto workspace settings are:
 
  yocto 'build' dir = \"${YOCTO_PFX}/${BUILD_DIR}\"
+ pwd = $(pwd)
 
+This implies that the recipe dir tree and files will be created there.
 If this is fine, press [Enter] to continue,
 else press ^C to abort, then go to the file named 'common' and
 fix the value of the variables YOCTO_PFX and BUILD_DIR there,
 then retry...
 
-Now press [Enter] to continue or ^C to abort ...
-"
+Now press [Enter] to continue or ^C to abort ... "
 read
 
 [ $# -lt 2 ] && {
@@ -224,13 +240,6 @@ export layer_token2=$(echo "${LAYER}" |cut -d"-" -f2)
 }
 
 TOP=$(pwd)
-[ ! -d ${YOCTO_PFX} ] && {
-  echo "${name}: ERROR: the 'yocto' build area specified
- \"${YOCTO_PFX}\"
-does not exist. Pl setup the yocto workspace first and then run this tool..."
-  exit 1
-}
-
 cd ${YOCTO_PFX}/${BUILD_DIR} || exit 1
 echo "Base Yocto workspace <pfx/build-dir> ::
 ${YOCTO_PFX}/${BUILD_DIR}
@@ -247,7 +256,9 @@ add_to_files_dir
 gen_recipe_file
 
 echo
-[ ${WARN} -ne 0 ] && echo "${name}: Note: some Warnings were generated"
+[ ${WARN} -ne 0 ] && echo "
+*** ${name}: Note: some WARNings were generated ***
+"
 echo "Layer \"$1\" recipe \"${RCP_NAME}\" setup:
 "
 tree ${YOCTO_PFX}/${BUILD_DIR}/${LAYER}/recipes-${layer_token2}
@@ -256,8 +267,12 @@ cd ${TOP}
 
 echo "${name}: Don't forget to:
  a) update the recipe file(s)
- b) update your ${BUILD_DIR}/conf/local.conf file to include the recipe in the build
+ b) update your ${BUILD_DIR}/conf/bblayers.conf file to include the layer that
+    contains this recipe in the build
+ c) update your ${BUILD_DIR}/conf/local.conf file to include the recipe in the build
     (typically via a \"IMAGE_INSTALL_append = \" \"${RCP_NAME}\"
- c) rebuild the project and test
+  TIP: doing a 'bitbake-layers show-recipes | grep xxx' one can check if the recipr's
+  installed
+ d) rebuild the project and test
  "
 exit 0
