Improvements as suggested by shellcheck

diff --git a/yocto_tools/yct_recipe_gen b/yocto_tools/yct_recipe_gen
--- a/yocto_tools/yct_recipe_gen
+++ b/yocto_tools/yct_recipe_gen
@@ -3,9 +3,9 @@
 # A very simple Yocto recipe generator script.
 # (c) Kaiwan N Billimoria, kaiwanTECH
 # License: dual MIT | Apache
-name=$(basename $0)
-PFX=$(dirname $(which $0))    # dir in which the common code and tools reside
-source ${PFX}/common || {
+name=$(basename "$0")
+PFX=$(dirname "$(which "$0")")    # dir in which the common code and tools reside
+source "${PFX}"/common || {
   echo "${name}: could not source 'common', aborting..." ; exit 1
 }
 WARN=0
@@ -17,15 +17,15 @@ local conf_file=${YOCTO_DIR}/${LAYER}/conf/layer.conf
 dprint "conf_file = ${conf_file}"
 echo
 echo "[+] Create layer's layer.conf file"
-[ -f ${YOCTO_DIR}/${LAYER}/conf/layer.conf ] && {
+[ -f "${YOCTO_DIR}"/"${LAYER}"/conf/layer.conf ] && {
   QP
   echo " *WARNING* skipping as layer.conf file already exists:"
-  ls -l ${conf_file}
+  ls -l "${conf_file}"
   WARN=1
   return
 }
 
-cd ${YOCTO_DIR}/${LAYER} || exit 1
+cd "${YOCTO_DIR}"/"${LAYER}" || exit 1
 #pwd
 mkdir -p conf
 rm -f conf/layer.conf 2>/dev/null
@@ -58,9 +58,9 @@ echo
 echo "[+] Add required files to the meta-<lyr>/recipes-<rcp>/files directory"
 
 local wd=800 ht=450
-local MORE=0 RCP_FILES RCPF_ARR re
+local RCP_FILES RCPF_ARR re
 
-while [ true ] ; do
+while true ; do
   RCP_FILES=$(yad --file-selection --multiple  \
        --center --width=${wd} --height=${ht} \
        --title="${name}: Select required files for 'files' dir (for ${LAYER}:${RCP_NAME})" 2>/dev/null)
@@ -71,18 +71,20 @@ while [ true ] ; do
        # ref: https://stackoverflow.com/questions/918886/how-do-i-split-a-string-on-a-delimiter-in-bash
     for RFIL in "${RCPF_ARR[@]}"
     do
-      printf "  %40s -> %30s\n" ${RFIL} ${RCP_FILES_DIR}
-      cp -a ${RFIL} ${RCP_FILES_DIR}/
+      printf "  %40s -> %30s\n" "${RFIL}" "${RCP_FILES_DIR}"
+      cp -a "${RFIL}" "${RCP_FILES_DIR}"/
     done
     unset IFS
   }
   echo -n "Add more files to recipe's 'files' dir? [y/N] "
-  read re
+  read -r re
   #echo "re = ${re}"
-  [ "${re}" != "y" -a "${re}" != "Y" ] && break
+  if [ "${re}" != "y" ] && [ "${re}" != "Y" ] ; then
+    break
+  fi
 done
 
-ls -l ${RCP_FILES_DIR}/
+ls -l "${RCP_FILES_DIR}"/
 echo
 }
 
@@ -97,12 +99,12 @@ local recipe_file=${YOCTO_DIR}/${LAYER}/recipes-${layer_token2}/${RCP_NAME}/${RC
 # TODO : TEMP
 #rm -f ${recipe_file}
 
-[ -f ${recipe_file} ] && {
+[ -f "${recipe_file}" ] && {
   QP
   echo "
 *WARNING* skipping as recipe file already exists:
 "
-  ls -l ${recipe_file}
+  ls -l "${recipe_file}"
   WARN=1
   return
 }
@@ -110,23 +112,23 @@ local recipe_file=${YOCTO_DIR}/${LAYER}/recipes-${layer_token2}/${RCP_NAME}/${RC
 #-- Get the 'files' dir content
 local fname
 
-local tmpf=$(tempfile)
-ls ${RCP_FILES_DIR} > ${tmpf}
+local tmpf=$(mktemp)
+ls "${RCP_FILES_DIR}" > "${tmpf}"
 
 local SRCURI_FILES
-for fname in $(cat ${tmpf})
+for fname in $(cat "${tmpf}")
 do
   #echo "fname : ${fname}"
   SRCURI_FILES="${SRCURI_FILES} file://${fname}"
 done
 SRCURI_FILES="${SRCURI_FILES} \\"
-rm -f ${tmpf}
+rm -f "${tmpf}"
 #echo "
 #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 #SRCURI_FILES : ${SRCURI_FILES}
 #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
 
-cat << @EOF@ > ${recipe_file}
+cat << @EOF@ > "${recipe_file}"
 # Recipe generated by ${name}
 # (c) kaiwanTECH
 # $(date)
@@ -134,12 +136,20 @@ DESCRIPTION = ""
 
 HOMEPAGE = ""
 
-# NOTE: LICENSE is being set to "CLOSED" to allow you to at least start building - if
-# this is not accurate with respect to the licensing of the software being built (it
-# will not be in most cases) you must specify the correct value before using this
-# recipe for anything other than initial testing/development!
-LICENSE = "CLOSED"
-LIC_FILES_CHKSUM = ""
+# NOTE: 
+# We set - and comment out - LICENSE to "CLOSED" to allow you to at least start
+# building - if this is not accurate with respect to the licensing of the
+# software being built (it will not be in most cases) you must specify the
+# correct value before using this recipe for anything other than initial
+# testing/development!
+#LICENSE = "CLOSED"
+#LIC_FILES_CHKSUM = ""
+# LICENSE set to 'Dual MIT/GPL'; change if you wish...
+LICENSE = "GPL-2.0 | MIT"
+LIC_FILES_CHKSUM = "\\
+	file://\${COREBASE}/meta/files/common-licenses/GPL-2.0;md5=801f80980d171dd6425610833a22dbe6 \\
+	file://\${COREBASE}/meta/files/common-licenses/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302 \\
+	"
 
 # Fill dependencies for this recipe;
 # f.e. = "bash dpkg python"
@@ -186,30 +196,34 @@ do_install () {
 	:
 }
 @EOF@
-ls -l ${recipe_file}
+ls -l "${recipe_file}"
 }
 
 
 ### 'main'
 
+echo "dbg = ${DEBUG}"
 which yad >/dev/null || {
   echo "${name}: 'yad' (yet another dialog) util missing, pl install package and retry..."
   exit 1
 }
 
 [ -z "${YOCTO_DIR}" ] && YOCTO_DIR=${YOCTO_PFX}/${BUILD_DIR}
-export ${YOCTO_DIR}
-[ ! -d ${YOCTO_DIR} ] && {
-  echo "${name}: ERROR: the 'yocto' build area specified
+export YOCTO_DIR
+[ ! -d "${YOCTO_DIR}" ] && {
+  echo "${name}: ERROR: the 'yocto' build area (auto) specified
  \"${YOCTO_DIR}\"
-does not exist. Pl setup the yocto workspace first and then run this tool...
-[Tips:
-- set (export) the environment variable YOCTO_DIR prior to running this tool]
+does not exist (the default value is in the 'common' script).
+
+Pl setup the yocto workspace first and then run this tool...
+Tips:
+- override the YOCTO_DIR default by setting (export) the env var YOCTO_DIR
+  prior to running this tool
 - for 'debug' mode, set env var DEBUG=1 while running"
   exit 1
 }
 
-echo "              +++ !NOTE Carefully Please! +++
+echo " +++ NOTE Carefully Please +++
 The current yocto workspace settings are:
 
  yocto 'build' dir = \"${YOCTO_DIR}\"
@@ -223,7 +237,7 @@ else press ^C to abort, then set (export) the environment variable YOCTO_DIR pri
 to running this tool and retry...
 
 Now press [Enter] to continue or ^C to abort ... "
-read
+read -r
 
 [ $# -lt 2 ] && {
   echo "Usage: ${name} meta-<layername> recipe-name"
@@ -249,7 +263,7 @@ export layer_token2=$(echo "${LAYER}" |cut -d"-" -f2)
 dprint "layer_token2 = ${layer_token2}"
 
 TOP=$(pwd)
-cd ${YOCTO_DIR} || exit 1
+cd "${YOCTO_DIR}" || exit 1
 echo "Base Yocto workspace <pfx/build-dir> ::
 ${YOCTO_DIR}
 "
@@ -257,15 +271,13 @@ ${YOCTO_DIR}
 #-- Create the basic tree
 RCP_FILES_DIR=${YOCTO_DIR}/${LAYER}/recipes-${layer_token2}/${RCP_NAME}/files
 dprint "RCP_FILES_DIR = ${RCP_FILES_DIR}"
-mkdir -p ${RCP_FILES_DIR} || {
+mkdir -p "${RCP_FILES_DIR}" || {
   echo "Creating recipe dir \"${RCP_FILES_DIR}\" failed, aborting..."
   exit 1
 }
 
-[ 1 -eq 1 ] && {
 setup_conf_layer_file
 add_to_files_dir
-}
 gen_recipe_file
 
 echo
@@ -274,9 +286,9 @@ echo
 "
 echo "Layer \"$1\" recipe \"${RCP_NAME}\" setup:
 "
-tree ${YOCTO_DIR}/${LAYER}/recipes-${layer_token2}
+tree "${YOCTO_DIR}"/"${LAYER}"/recipes-"${layer_token2}"
 
-cd ${TOP}
+cd "${TOP}"
 
 echo "${name}: Don't forget to:
  a) update the recipe file(s)
