Add the YOCTO_DIR env var to specify workspace; add debug prints

diff --git a/yocto_tools/yct_recipe_gen b/yocto_tools/yct_recipe_gen
--- a/yocto_tools/yct_recipe_gen
+++ b/yocto_tools/yct_recipe_gen
@@ -1,6 +1,8 @@
 #!/bin/bash
 # yct_recipe_gen
-
+# A very simple Yocto recipe generator script.
+# (c) Kaiwan N Billimoria, kaiwanTECH
+# License: dual MIT | Apache
 name=$(basename $0)
 PFX=$(dirname $(which $0))    # dir in which the common code and tools reside
 source ${PFX}/common || {
@@ -11,11 +13,11 @@ WARN=0
 #-- Create the conf/layer.conf file
 setup_conf_layer_file()
 {
-local conf_file=${YOCTO_PFX}/${BUILD_DIR}/${LAYER}/conf/layer.conf
-
+local conf_file=${YOCTO_DIR}/${LAYER}/conf/layer.conf
+dprint "conf_file = ${conf_file}"
 echo
 echo "[+] Create layer's layer.conf file"
-[ -f ${YOCTO_PFX}/${BUILD_DIR}/${LAYER}/conf/layer.conf ] && {
+[ -f ${YOCTO_DIR}/${LAYER}/conf/layer.conf ] && {
   QP
   echo " *WARNING* skipping as layer.conf file already exists:"
   ls -l ${conf_file}
@@ -23,13 +25,15 @@ echo "[+] Create layer's layer.conf file"
   return
 }
 
-cd ${YOCTO_PFX}/${BUILD_DIR}/${LAYER} || exit 1
+cd ${YOCTO_DIR}/${LAYER} || exit 1
 #pwd
 mkdir -p conf
-rm -f conf/layer.conf
+rm -f conf/layer.conf 2>/dev/null
+touch conf/layer.conf
 
 # TODO : tune layer prio, compat
-cat <<- @EOF@ > ${conf_file}
+#cat <<- @EOF@ > ${conf_file}
+cat <<- @EOF@ > conf/layer.conf
 	# We have a conf and classes directory, add to BBPATH
 	BBPATH .= ":\${LAYERDIR}"
 
@@ -44,7 +48,7 @@ cat <<- @EOF@ > ${conf_file}
 	LAYER_DEPENDS_${layer_token2} = "core"
 	LAYERSERIES_COMPAT_${layer_token2} = "thud warrior zeus"
 @EOF@
-ls -l ${conf_file}
+ls -l conf/layer.conf
 }
 
 #-- Populate the meta-<lyr> / recipes-<rcp> / files  directory with reqd files
@@ -88,7 +92,7 @@ gen_recipe_file()
 echo
 echo "[+] Generate the layer's recipe file"
 
-local recipe_file=${YOCTO_PFX}/${BUILD_DIR}/${LAYER}/recipes-${layer_token2}/${RCP_NAME}/${RCP_NAME}.bb
+local recipe_file=${YOCTO_DIR}/${LAYER}/recipes-${layer_token2}/${RCP_NAME}/${RCP_NAME}.bb
 
 # TODO : TEMP
 #rm -f ${recipe_file}
@@ -189,30 +193,34 @@ ls -l ${recipe_file}
 ### 'main'
 
 which yad >/dev/null || {
-  echo "${name}: 'yad' (yet another dialog) util missing, pl install and retry..."
+  echo "${name}: 'yad' (yet another dialog) util missing, pl install package and retry..."
   exit 1
 }
 
-[ ! -d ${YOCTO_PFX}/${BUILD_DIR} ] && {
+[ -z "${YOCTO_DIR}" ] && YOCTO_DIR=${YOCTO_PFX}/${BUILD_DIR}
+export ${YOCTO_DIR}
+[ ! -d ${YOCTO_DIR} ] && {
   echo "${name}: ERROR: the 'yocto' build area specified
- \"${YOCTO_PFX}/${BUILD_DIR}\"
+ \"${YOCTO_DIR}\"
 does not exist. Pl setup the yocto workspace first and then run this tool...
-[go to the src file 'common' and fix the value of the variables
-YOCTO_PFX and BUILD_DIR there]"
+[Tips:
+- set (export) the environment variable YOCTO_DIR prior to running this tool]
+- for 'debug' mode, set env var DEBUG=1 while running"
   exit 1
 }
 
 echo "              +++ !NOTE Carefully Please! +++
 The current yocto workspace settings are:
 
- yocto 'build' dir = \"${YOCTO_PFX}/${BUILD_DIR}\"
- pwd = $(pwd)
+ yocto 'build' dir = \"${YOCTO_DIR}\"
 
-This implies that the recipe dir tree and files will be created there.
+[fyi, pwd = $(pwd)]
+
+This implies that the recipe dir tree and files will be created within the
+yocto 'build' dir displayed above.
 If this is fine, press [Enter] to continue,
-else press ^C to abort, then go to the file named 'common' and
-fix the value of the variables YOCTO_PFX and BUILD_DIR there,
-then retry...
+else press ^C to abort, then set (export) the environment variable YOCTO_DIR prior
+to running this tool and retry...
 
 Now press [Enter] to continue or ^C to abort ... "
 read
@@ -238,16 +246,21 @@ export layer_token2=$(echo "${LAYER}" |cut -d"-" -f2)
  meta-<foo> (<foo> part missing)"
   exit 1 
 }
+dprint "layer_token2 = ${layer_token2}"
 
 TOP=$(pwd)
-cd ${YOCTO_PFX}/${BUILD_DIR} || exit 1
+cd ${YOCTO_DIR} || exit 1
 echo "Base Yocto workspace <pfx/build-dir> ::
-${YOCTO_PFX}/${BUILD_DIR}
+${YOCTO_DIR}
 "
 
 #-- Create the basic tree
-RCP_FILES_DIR=${YOCTO_PFX}/${BUILD_DIR}/${LAYER}/recipes-${layer_token2}/${RCP_NAME}/files
-mkdir -p ${RCP_FILES_DIR}
+RCP_FILES_DIR=${YOCTO_DIR}/${LAYER}/recipes-${layer_token2}/${RCP_NAME}/files
+dprint "RCP_FILES_DIR = ${RCP_FILES_DIR}"
+mkdir -p ${RCP_FILES_DIR} || {
+  echo "Creating recipe dir \"${RCP_FILES_DIR}\" failed, aborting..."
+  exit 1
+}
 
 [ 1 -eq 1 ] && {
 setup_conf_layer_file
@@ -261,7 +274,7 @@ echo
 "
 echo "Layer \"$1\" recipe \"${RCP_NAME}\" setup:
 "
-tree ${YOCTO_PFX}/${BUILD_DIR}/${LAYER}/recipes-${layer_token2}
+tree ${YOCTO_DIR}/${LAYER}/recipes-${layer_token2}
 
 cd ${TOP}
 
@@ -270,9 +283,9 @@ echo "${name}: Don't forget to:
  b) update your ${BUILD_DIR}/conf/bblayers.conf file to include the layer that
     contains this recipe in the build
  c) update your ${BUILD_DIR}/conf/local.conf file to include the recipe in the build
-    (typically via a \"IMAGE_INSTALL_append = \" \"${RCP_NAME}\"
-  TIP: doing a 'bitbake-layers show-recipes | grep xxx' one can check if the recipr's
-  installed
- d) rebuild the project and test
+    (typically via a \"IMAGE_INSTALL_append = \" ${RCP_NAME}\"\"
+  TIP: doing a 'bitbake-layers show-recipes | grep xxx' one can check if layer
+  'xxx' is actually installed
+ d) rebuild the project with 'bitbake <image-name>' and test
  "
 exit 0
